/*
 *  Xen backend base class
 *
 *  Based on
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
 *
 * Copyright (C) 2016 EPAM Systems Inc.
 */

#ifndef INCLUDE_BACKENDBASE_HPP_
#define INCLUDE_BACKENDBASE_HPP_

#include <atomic>
#include <map>
#include <memory>
#include <string>
#include <utility>

#include "FrontendHandlerBase.hpp"
#include "XenException.hpp"
#include "XenStore.hpp"
#include "XenStat.hpp"
#include "Log.hpp"

namespace XenBackend {

/***************************************************************************//**
 * @defgroup Backend
 * Contains classes and primitives to create the full featured Xen backend.
 ******************************************************************************/

/***************************************************************************//**
 * Exception generated by BackendBase.
 * @ingroup Backend
 ******************************************************************************/
class BackendException : public XenException
{
	using XenException::XenException;
};

/***************************************************************************//**
 * The entry class to implement the backend.
 * The client should create a class inherited from BackendBase and implement
 * onNewFrontend() method.
 * Also the way in which the new domain is detected can be changed by overriding
 * getNewFrontend().
 * Example of the client backend class:
 *
 * @code{.cpp}
 * class MyBackend : public XenBackend::BackendBase
 * {
 *     using XenBackend::BackendBase::BackendBase;
 *
 * private:
 *
 *     void onNewFrontend(int domId, int id)
 *     {
 *         addFrontendHandler(FrontendHandlerPtr(
 *                            new MyFrontendHandler(domId, *this, id)));
 *     }
 * };
 * @endcode
 * @ingroup Backend
 ******************************************************************************/
class BackendBase
{
public:
	/**
	 * @param[in] domId      domain id
	 * @param[in] deviceName device name
	 * @param[in] id         instance id
	 */
	BackendBase(int domId, const std::string& deviceName, int id = 0);
	virtual ~BackendBase();

	/**
	 * Starts backend.
	 * This method is blocking and terminates in case of error or stop()
	 * is called from the another thread.
	 */
	void run();

	/**
	 * Stops backend.
	 */
	void stop();

	/**
	 * Returns backend device name
	 */
	const std::string& getDeviceName() const { return mDeviceName; }

	/**
	 * Returns instance id
	 */
	int getId() const { return mId; }

	/**
	 * Returns domain id
	 */
	int getDomId() const { return mDomId; }

protected:
	/**
	 * Is called periodically to check if a new frontend's appeared.
	 * In order to change the way a new domain is detected the client may
	 * override this method.
	 *
	 * @param[out] domId domain id
	 * @param[out] id    instance id
	 * @return <i>true</i> if new frontend is detected
	 */
	virtual bool getNewFrontend(int& domId, int& id);

	/**
	 * Is called when new frontend detected.
	 * Basically the client should create
	 * the instance of FrontendHandlerBase class and pass it to
	 * addFrontendHandler().
	 * @param[in] domId domain id
	 * @param[in] id    instance id
	 */
	virtual void onNewFrontend(int domId, int id) = 0;

	/**
	 * Adds new frontend handler
	 * @param[in] frontendHandler frontend instance
	 */
	void addFrontendHandler(FrontendHandlerPtr frontendHandler);

private:

	int cPollFrontendIntervalMs = 500; //!< Frontend poll interval in msec

	int mId;
	int mDomId;
	std::string mDeviceName;
	XenStore mXenStore;
	XenStat mXenStat;

	std::map<std::pair<int, int>, FrontendHandlerPtr> mFrontendHandlers;

	std::atomic_bool mTerminate;

	Log mLog;

	void createFrontendHandler(const std::pair<int, int>& ids);
	void checkTerminatedFrontends();
};

}

#endif /* INCLUDE_BACKENDBASE_HPP_ */
